"""add job_runs table

Revision ID: 009340715714
Revises: 55410f2764bb
Create Date: 2026-07-12 19:50:48.829341

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "009340715714"
down_revision: str | Sequence[str] | None = "55410f2764bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
