"""add token_snapshots table

Revision ID: 123a5848b397
Revises: def592c4ce88
Create Date: 2026-07-13 19:39:39.878006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '123a5848b397'
down_revision: Union[str, Sequence[str], None] = 'def592c4ce88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('liquidity_usd', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('volume_24h_usd', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('market_cap_usd', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('fdv_usd', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_snapshots_captured_at'), 'token_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_token_snapshots_token_id'), 'token_snapshots', ['token_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_snapshots_token_id'), table_name='token_snapshots')
    op.drop_index(op.f('ix_token_snapshots_captured_at'), table_name='token_snapshots')
    op.drop_table('token_snapshots')
    # ### end Alembic commands ###
