"""add contract_securities table

Revision ID: 2498f6dcb3be
Revises: 7cd4f96778ce
Create Date: 2026-07-14 19:19:12.133287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2498f6dcb3be'
down_revision: Union[str, Sequence[str], None] = '7cd4f96778ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_securities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('safety_score', sa.Integer(), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_honeypot', sa.Boolean(), nullable=False),
    sa.Column('is_mintable', sa.Boolean(), nullable=False),
    sa.Column('is_open_source', sa.Boolean(), nullable=False),
    sa.Column('buy_tax', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('sell_tax', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('owner_address', sa.String(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_securities_token_id'), 'contract_securities', ['token_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_securities_token_id'), table_name='contract_securities')
    op.drop_table('contract_securities')
    # ### end Alembic commands ###
