"""add social_scores, token_social_snapshots, token social link columns

Revision ID: 25781ba526d8
Revises: ca23305ec484
Create Date: 2026-07-16 15:20:43.994982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25781ba526d8'
down_revision: Union[str, Sequence[str], None] = 'ca23305ec484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
