"""index tokens.liquidity_usd

Revision ID: 2951b13ef6bd
Revises: a1632caa1009
Create Date: 2026-07-13 15:54:11.596808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2951b13ef6bd'
down_revision: Union[str, Sequence[str], None] = 'a1632caa1009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'liquidity_usd',
               existing_type=sa.NUMERIC(precision=38, scale=8),
               type_=sa.Numeric(precision=24, scale=8),
               existing_nullable=True)
    op.create_index(op.f('ix_tokens_liquidity_usd'), 'tokens', ['liquidity_usd'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_liquidity_usd'), table_name='tokens')
    op.alter_column('tokens', 'liquidity_usd',
               existing_type=sa.Numeric(precision=24, scale=8),
               type_=sa.NUMERIC(precision=38, scale=8),
               existing_nullable=True)
    # ### end Alembic commands ###
