"""add whale_events table

Revision ID: 7a016727fe05
Revises: b3c8f2a1d4e5
Create Date: 2026-07-16 12:22:10.270628

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7a016727fe05"
down_revision: str | Sequence[str] | None = "b3c8f2a1d4e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "whale_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("token_id", sa.UUID(), nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum("NEW_POSITION", "INCREASED", "DECREASED", name="whale_event_type_enum"),
            nullable=False,
        ),
        sa.Column("previous_balance", sa.Numeric(precision=36, scale=18), nullable=True),
        sa.Column("new_balance", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("change_pct", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("change_usd", sa.Numeric(precision=24, scale=2), nullable=True),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["token_id"], ["tokens.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_whale_events_detected_at"), "whale_events", ["detected_at"], unique=False
    )
    op.create_index(op.f("ix_whale_events_token_id"), "whale_events", ["token_id"], unique=False)
    op.create_index(op.f("ix_whale_events_wallet_id"), "whale_events", ["wallet_id"], unique=False)
    op.alter_column(
        "contract_securities",
        "flags",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contract_securities",
        "flags",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_whale_events_wallet_id"), table_name="whale_events")
    op.drop_index(op.f("ix_whale_events_token_id"), table_name="whale_events")
    op.drop_index(op.f("ix_whale_events_detected_at"), table_name="whale_events")
    op.drop_table("whale_events")
    # ### end Alembic commands ###
