"""increase numeric precision

Revision ID: 83a1eef06097
Revises: ae75d3e15699
Create Date: 2026-07-12 17:19:18.048695

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "83a1eef06097"
down_revision: str | Sequence[str] | None = "ae75d3e15699"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tokens",
        "liquidity_usd",
        existing_type=sa.NUMERIC(precision=24, scale=8),
        type_=sa.Numeric(precision=38, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "tokens",
        "market_cap_usd",
        existing_type=sa.NUMERIC(precision=24, scale=8),
        type_=sa.Numeric(precision=38, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "tokens",
        "fdv_usd",
        existing_type=sa.NUMERIC(precision=24, scale=8),
        type_=sa.Numeric(precision=38, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "tokens",
        "volume_24h_usd",
        existing_type=sa.NUMERIC(precision=24, scale=8),
        type_=sa.Numeric(precision=38, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "tokens",
        "price_usd",
        existing_type=sa.NUMERIC(precision=36, scale=18),
        type_=sa.Numeric(precision=38, scale=18),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tokens",
        "price_usd",
        existing_type=sa.Numeric(precision=38, scale=18),
        type_=sa.NUMERIC(precision=36, scale=18),
        existing_nullable=True,
    )
    op.alter_column(
        "tokens",
        "volume_24h_usd",
        existing_type=sa.Numeric(precision=38, scale=8),
        type_=sa.NUMERIC(precision=24, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "tokens",
        "fdv_usd",
        existing_type=sa.Numeric(precision=38, scale=8),
        type_=sa.NUMERIC(precision=24, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "tokens",
        "market_cap_usd",
        existing_type=sa.Numeric(precision=38, scale=8),
        type_=sa.NUMERIC(precision=24, scale=8),
        existing_nullable=True,
    )
    op.alter_column(
        "tokens",
        "liquidity_usd",
        existing_type=sa.Numeric(precision=38, scale=8),
        type_=sa.NUMERIC(precision=24, scale=8),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
