"""add alpha_scores table

Revision ID: 9a7bef68c5fd
Revises: 0bc16a95d4a5
Create Date: 2026-07-14 01:14:32.544230

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "9a7bef68c5fd"
down_revision: str | Sequence[str] | None = "0bc16a95d4a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
