"""add narrative_classifications table

Revision ID: a5ccde711962
Revises: 25781ba526d8
Create Date: 2026-07-16 20:14:12.151798

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5ccde711962"
down_revision: str | Sequence[str] | None = "25781ba526d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "narrative_classifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("token_id", sa.UUID(), nullable=False),
        sa.Column(
            "primary_narrative",
            sa.Enum(
                "AI",
                "DEFI",
                "GAMING",
                "RWA",
                "INFRASTRUCTURE",
                "ZK",
                "PRIVACY",
                "DEPIN",
                "MEME",
                "LAYER2",
                "BITCOIN_ECOSYSTEM",
                "OTHER",
                name="narrative_enum",
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("reasoning", sa.String(length=280), nullable=False),
        sa.Column(
            "classified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["token_id"], ["tokens.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_narrative_classifications_primary_narrative"),
        "narrative_classifications",
        ["primary_narrative"],
        unique=False,
    )
    op.create_index(
        op.f("ix_narrative_classifications_token_id"),
        "narrative_classifications",
        ["token_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_narrative_classifications_token_id"), table_name="narrative_classifications"
    )
    op.drop_index(
        op.f("ix_narrative_classifications_primary_narrative"),
        table_name="narrative_classifications",
    )
    op.drop_table("narrative_classifications")
    # ### end Alembic commands ###
