"""create tokens table

Revision ID: ae75d3e15699
Revises:
Create Date: 2026-07-12 13:18:11.585704

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae75d3e15699"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "chain",
            sa.Enum(
                "ETHEREUM",
                "BASE",
                "SOLANA",
                "BNB_CHAIN",
                "ARBITRUM",
                "POLYGON",
                "AVALANCHE",
                "OPTIMISM",
                name="chain_enum",
            ),
            nullable=False,
        ),
        sa.Column("contract_address", sa.String(length=64), nullable=False),
        sa.Column("pair_address", sa.String(length=64), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("decimals", sa.Integer(), nullable=False),
        sa.Column("dex", sa.String(length=64), nullable=True),
        sa.Column("liquidity_usd", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("market_cap_usd", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("fdv_usd", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("volume_24h_usd", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("price_usd", sa.Numeric(precision=36, scale=18), nullable=True),
        sa.Column("holder_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chain", "contract_address", name="uq_token_chain_address"),
    )
    op.create_index(op.f("ix_tokens_chain"), "tokens", ["chain"], unique=False)
    op.create_index(
        op.f("ix_tokens_contract_address"), "tokens", ["contract_address"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tokens_contract_address"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_chain"), table_name="tokens")
    op.drop_table("tokens")
    # ### end Alembic commands ###
