"""index tokens.liquidity_usd

Revision ID: be436e3727bb
Revises: 2951b13ef6bd
Create Date: 2026-07-13 15:56:53.451677

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "be436e3727bb"
down_revision: str | Sequence[str] | None = "2951b13ef6bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
