"""add social_scores, token_social_snapshots tables, token social link columns

Revision ID: ca23305ec484
Revises: 7a016727fe05
Create Date: 2026-07-16 13:21:49.435181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca23305ec484'
down_revision: Union[str, Sequence[str], None] = '7a016727fe05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('factor_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('possible_inorganic_growth', sa.Boolean(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_scores_token_id'), 'social_scores', ['token_id'], unique=True)
    op.create_table('token_social_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('message_count_24h', sa.Integer(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_social_snapshots_scanned_at'), 'token_social_snapshots', ['scanned_at'], unique=False)
    op.create_index(op.f('ix_token_social_snapshots_token_id'), 'token_social_snapshots', ['token_id'], unique=False)
    op.add_column('tokens', sa.Column('telegram_url', sa.String(length=256), nullable=True))
    op.add_column('tokens', sa.Column('twitter_handle', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'twitter_handle')
    op.drop_column('tokens', 'telegram_url')
    op.drop_index(op.f('ix_token_social_snapshots_token_id'), table_name='token_social_snapshots')
    op.drop_index(op.f('ix_token_social_snapshots_scanned_at'), table_name='token_social_snapshots')
    op.drop_table('token_social_snapshots')
    op.drop_index(op.f('ix_social_scores_token_id'), table_name='social_scores')
    op.drop_table('social_scores')
    # ### end Alembic commands ###
