"""add wallets and wallet_holdings tables

Revision ID: d4931ebca9a7
Revises: 9a7bef68c5fd
Create Date: 2026-07-14 17:10:23.415302

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d4931ebca9a7"
down_revision: str | Sequence[str] | None = "9a7bef68c5fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "chain",
            postgresql.ENUM(
                "ETHEREUM",
                "BASE",
                "SOLANA",
                "BNB_CHAIN",
                "ARBITRUM",
                "POLYGON",
                "AVALANCHE",
                "OPTIMISM",
                name="chain_enum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("address", sa.String(length=64), nullable=False),
        sa.Column(
            "wallet_type",
            sa.Enum(
                "UNKNOWN",
                "WHALE",
                "SMART_MONEY",
                "VC",
                "EXCHANGE",
                "INFLUENCER",
                "EARLY_ADOPTER",
                name="wallet_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chain", "address", name="uq_wallet_chain_address"),
    )
    op.create_index(op.f("ix_wallets_address"), "wallets", ["address"], unique=False)
    op.create_index(op.f("ix_wallets_chain"), "wallets", ["chain"], unique=False)
    op.create_table(
        "wallet_holdings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("token_id", sa.UUID(), nullable=False),
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("approximate_balance", sa.Numeric(precision=36, scale=18), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column(
            "scanned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["token_id"], ["tokens.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_id", "wallet_id", name="uq_holding_token_wallet"),
    )
    op.create_index(
        op.f("ix_wallet_holdings_token_id"), "wallet_holdings", ["token_id"], unique=False
    )
    op.create_index(
        op.f("ix_wallet_holdings_wallet_id"), "wallet_holdings", ["wallet_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wallet_holdings_wallet_id"), table_name="wallet_holdings")
    op.drop_index(op.f("ix_wallet_holdings_token_id"), table_name="wallet_holdings")
    op.drop_table("wallet_holdings")
    op.drop_index(op.f("ix_wallets_chain"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_address"), table_name="wallets")
    op.drop_table("wallets")
    # ### end Alembic commands ###
