"""index tokens.liquidity_usd

Revision ID: def592c4ce88
Revises: be436e3727bb
Create Date: 2026-07-13 17:12:58.823894

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "def592c4ce88"
down_revision: str | Sequence[str] | None = "be436e3727bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
