"""add narrative_classifications table

Revision ID: f1170bc03530
Revises: a5ccde711962
Create Date: 2026-07-16 20:31:01.680442

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f1170bc03530"
down_revision: str | Sequence[str] | None = "a5ccde711962"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
