"""add token_snapshots table

Revision ID: fb8df47b7662
Revises: 123a5848b397
Create Date: 2026-07-13 19:50:49.763756

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "fb8df47b7662"
down_revision: str | Sequence[str] | None = "123a5848b397"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
